version: "3"

tasks:
  start:
    aliases:
      - start
    cmds:
      - DATABASE_PORT=5432 DATABASE_USER=postgres DATABASE_PASSWORD=password DATABASE_NAME=coin SERVER_PORT=8081 SECRET=0hTBL4aYdp0EtnQS7LmQaxWWDZ3k3CRo/ibK1nOTnCM= DATABASE_HOST=localhost go run cmd/main.go
